# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Intro_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('sequence_of_apps', otree.db.models.LongStringField(null=True)),
                ('aim', otree.db.models.IntegerField(choices=[[1, 'Finish first'], [2, 'Achieve high forecast accuracy of wine demand'], [3, 'Meet expectations of other obligations in my schedule']], null=True, verbose_name='What should you aim for in this game?')),
                ('mechanism', otree.db.models.IntegerField(choices=[[1, 'The number is calculated by an algorithm.'], [2, 'A friend of yours tells you about his thoughts.'], [3, 'An expert calculates according to his market research and expectations.']], null=True, verbose_name='Where does the reference value come from?')),
                ('accuracy', otree.db.models.IntegerField(choices=[[1, 'You must overtake the advice number.'], [2, 'You can decide whether taking the advice number into account or not.'], [3, 'Ask your neighbour what the right value might be.']], null=True, verbose_name='How do you make your decision?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Intro.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_player', to='otree.Session')),
            ],
            options={
                'db_table': 'Intro_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intro_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Intro_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intro.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intro.Subsession'),
        ),
    ]
