# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postquestionnaire_group', to='otree.Session')),
            ],
            options={
                'db_table': 'postquestionnaire_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('gender', otree.db.models.IntegerField(choices=[[1, 'Male'], [2, 'Female'], [3, 'Other']], null=True, verbose_name='1. What is your gender?')),
                ('age', otree.db.models.IntegerField(choices=[[1, '18-19'], [2, '20-21'], [3, '22-23'], [4, '24-25'], [5, '26-27'], [6, '28-29'], [7, '30-31'], [8, '32-33'], [9, '34-35'], [10, '36-37'], [11, '38-39'], [12, '40-41'], [13, '42-43'], [14, '44-45'], [15, '46-47'], [16, '48-49'], [17, '50-51'], [18, '52-53'], [19, '54-55'], [20, '56-57'], [21, '58-59'], [22, '60-61'], [23, '62-63'], [24, '64-65'], [25, '66-67'], [26, '68-69'], [27, '70-71'], [28, '72-73'], [29, '74-75'], [30, '76-77'], [31, '78-79'], [32, '80-81']], null=True, verbose_name='2. How old are you?')),
                ('education', otree.db.models.IntegerField(choices=[[1, 'Apprenticeship'], [2, 'Matriculation standard/ Highschool'], [3, 'Bachelor or equivalent'], [4, 'Master or equivalent'], [5, 'PhD/Doctorate and above']], null=True, verbose_name='3. What is your highest education?')),
                ('experience', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], verbose_name='4. Do you have any experience in forecasting?')),
                ('forecasting_years', otree.db.models.IntegerField(choices=[[0, 'None'], [1, 'Up to 1 year'], [2, '1-2 years'], [3, '2-5 years'], [4, 'More than 5 years']], null=True, verbose_name='4.1 How much experience in forecasting do you have?')),
                ('course', otree.db.models.IntegerField(choices=[[1, 'From courses and trainings'], [2, 'From work'], [3, 'From both'], [4, 'I don`t have any experience']], null=True, verbose_name='4.2 Where have you gained the experience in forecasting?')),
                ('calculator', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], verbose_name='5. Did you calculate with paper and pen?')),
                ('prio', otree.db.models.LongStringField(null=True, verbose_name='6. What kind of information exchange did you prefer in the game? Please explain why.')),
                ('other', otree.db.models.LongStringField(null=True, verbose_name='7. Would you like to have a different way of information exchange? Please explain why.')),
                ('system', otree.db.models.LongStringField(null=True, verbose_name='8. What do you think about the "Referring Information" (black box) in general?')),
                ('meeting1', otree.db.models.LongStringField(null=True, verbose_name='10. How did you feel about the benefit of regular meetings instead of the "Referring Information"?')),
                ('meeting2', otree.db.models.IntegerField(choices=[[0, 'I would not want to replace the meetings by the information provided by the system (="Referring Information").'], [1, 'I see the same influence from both information sources.'], [2, 'The "Referring Information" is more efficient than regular meetings.'], [3, 'I would prefer to ask for information when I need it.']], null=True, verbose_name='11. What statement fits most to your experience in this game?')),
                ('personality1', otree.db.models.IntegerField(choices=[[0, 'Details of a specific task'], [1, 'General overview of possible solution approaches']], null=True, verbose_name='12. What is more important for you at work?')),
                ('personality2', otree.db.models.IntegerField(choices=[[0, 'Individual coaching for the duration of a project'], [1, 'Independent work on a project']], null=True, verbose_name='13. Which situation do you prefer?')),
                ('personality3', otree.db.models.IntegerField(choices=[[0, 'Rapidly changing tasks that create progress'], [1, 'Focusing alone on the task to create exellence'], [2, 'Comfortable and predictable tasks that support the team'], [3, 'Interacting with many people to create new ideas and energy']], null=True, verbose_name='14. What type of work do you enjoy most?')),
                ('personality4', otree.db.models.IntegerField(choices=[[0, 'Finding a small group of people you already know'], [1, 'Seeking a good point to observe the event'], [2, 'Meeting and talking to as many people as possible'], [3, 'Going to the people who are the reason why you are here']], null=True, verbose_name='15. How do you behave at an event where are mostly people you haven`t met before?')),
                ('open', otree.db.models.LongStringField(null=True, verbose_name='16. Please leave here any other additional comment regarding the game.')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postquestionnaire.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postquestionnaire_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postquestionnaire_player', to='otree.Session')),
            ],
            options={
                'db_table': 'postquestionnaire_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postquestionnaire_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'postquestionnaire_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postquestionnaire.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postquestionnaire.Subsession'),
        ),
    ]
