# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentb_group', to='otree.Session')),
            ],
            options={
                'db_table': 'ExperimentB_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('sequence_of_apps', otree.db.models.LongStringField(null=True)),
                ('JulyForecast', otree.db.models.IntegerField(null=True, verbose_name='How much wine do you need? [bottles]')),
                ('AugustForecast', otree.db.models.IntegerField(null=True, verbose_name='How much wine do you need? [bottles]')),
                ('SeptemberForecast', otree.db.models.IntegerField(null=True, verbose_name='How much wine do you need? [bottles]')),
                ('OctoberForecast', otree.db.models.IntegerField(null=True, verbose_name='How much wine do you need? [bottles]')),
                ('NovemberForecast', otree.db.models.IntegerField(null=True, verbose_name='How much wine do you need? [bottles]')),
                ('DecemberForecast', otree.db.models.IntegerField(null=True, verbose_name='How much wine do you need? [bottles]')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExperimentB.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentb_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentb_player', to='otree.Session')),
            ],
            options={
                'db_table': 'ExperimentB_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experimentb_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'ExperimentB_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExperimentB.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExperimentB.Subsession'),
        ),
    ]
